@startuml usecade_user
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

left to right direction
actor "User" as fc
database "Database" as DB

rectangle Authentification {
  usecase "Login and Logout" as UC1
  usecase "Change Password" as UC2
  usecase "Register New User" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3

UC1 ..> DB
UC2 ..> DB 
UC3 ..> DB

rectangle Commitee{
    usecase "edit committee" as CS 
    usecase "delete commitee" as ED 
    usecase "modify commitee" as MP 

}

fc --> CS
fc --> ED 
fc --> MP 

CS ..> DB
ED ..> DB
MP ..> DB

rectangle CommiteeMember{
  usecase "create member" as CM 
  usecase "modify member" as MM 
  usecase "delete member"  as DM 
}

fc --> CM 
fc --> MM 
fc --> DM 

CM ..> DB
MM ..> DB
DM ..> DB 

rectangle Scholarship{
  usecase "establish scholarship" as ES 
  usecase "modify scholarship"  as MS
  usecase "Delete Scholarship" as DS 
  usecase "Designate Scholarship" as DES 
  usecase "award scholarship"  as WS 
}


fc --> ES 
fc -->  MS 
fc --> DS 
fc --> DES 
fc --> WS 

WS ..> DB
ES ..> DB
MS ..> DB
DES ..> DB
DS ..> DB 




@enduml
