@startuml commitee_uml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

left to right direction
actor "Commitee" as coo

usecase "Login and Logout" as UC1
usecase "Change Password" as UC2
usecase "Register New User" as UC3

coo --> UC1 
coo --> UC3
coo --> UC2

usecase "edit committee" as CS 
usecase "delete commitee" as ED 
usecase "modify commitee" as MP 

coo --> CS 
coo --> ED 
coo --> MP 


  usecase "establish scholarship" as ES 
  usecase "modify scholarship"  as MS
  usecase "Delete Scholarship" as DS 
  usecase "Designate Scholarship" as DES 
  usecase "award scholarship"  as WS 

coo --> ES 
coo --> MS 
coo --> DS 
coo  --> DES 
coo --> WS 






@enduml