@startuml kkk
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml


entity Complainant{
    id:pk 
    username : CharField 
    first_name : CharField
    last_name : CharField
    email : EmailField 
    password : CharField
    
}

entity Committee{
    id:pk 
    username : CharField 
    first_name : CharField
    last_name : CharField
    email : EmailField 
    password : CharField
    
}


entity Admin{
    id:pk 
    username : CharField 
    first_name : CharField
    last_name : CharField
    email : EmailField 
    password : CharField
    
}





entity Inquiry{
    id:pk 
    inqury_details :  CharField
    date_submited :  DateTime 
    commitee_id : ForeignKey(Committee)
    student_id :  ForeignKey(Complainant)



}

Committee||..|{ Inquiry
Complainant||..|{ Inquiry


entity Feedback{
    id:pk 
    inquiry_id :  ForeignKey(Inquiry)
    commitee_id :  ForeignKey(Committee)
    feeback_details :  CharField
    feedback_time :  DateTime


}

Inquiry||..|{ Feedback




entity Response{
    id:pk 
    feedback_id : ForeignKey(Feedback)
    response : CharField
    response_date :  DateTime
}

Feedback||..|{ Response





@enduml