@startuml usecade_user
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

left to right direction
actor "User" as fc


usecase "Login and Logout" as UC1
usecase "Change Password" as UC2
usecase "Register New User" as UC3

fc --> UC1
fc --> UC2
fc --> UC3

UC1 ..> DB
UC2 ..> DB 
UC3 ..> DB

rectangle Complaints{
    usecase "submit complaints" as CS 
    usecase "Check progress" as ED 
    usecase "delete complaints" as MP 
    usecase "modify complaints" as DP
    

}

fc --> CS
fc --> ED 
fc --> MP 
fc -->  DP 



CS ..> DB
ED ..> DB
MP ..> DB
DP ..> DB



rectangle FeedBack{
    usecase "check Feedback" as CF 
    usecase "reply to feedback" as RF
}

fc --> CF 
fc --> RF

CF ..> DB
RF ..> DB


rectangle Response{
    usecase "check response" as cc 
    usecase "reply response" as RC
}

fc ..> cc
fc ..> RC 
cc ..> DB 
RC ..> DB

@enduml
